add scraper for north rhine-westfalia gtfs feed (:de:)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -85,12 +85,12 @@ jobs:
         DO_SPACES_BUCKET_NAME: ${{ secrets.DO_SPACES_BUCKET_NAME }}
       run: |
         set -e;
-        npm run fetch-gtfs;
+        npm run fetch-de-gtfs;
         currentobj=$(aws s3api head-object --bucket $DO_SPACES_BUCKET_NAME --key gtfs-germany.zip);
-        newhash=$(cat gtfs.zip | md5sum);
+        newhash=$(cat de-gtfs.zip | md5sum);
         if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
         then
-          aws s3 cp --acl public-read gtfs.zip s3://"$DO_SPACES_BUCKET_NAME"/gtfs-germany.zip
+          aws s3 cp --acl public-read de-gtfs.zip s3://"$DO_SPACES_BUCKET_NAME"/gtfs-germany.zip
         else
           echo 'file unchanged, skipping.'
         fi;
@@ -103,12 +103,12 @@ jobs:
         DO_SPACES_BUCKET_NAME: ${{ secrets.DO_SPACES_BUCKET_NAME }}
       run: |
         set -e;
-        npm run fetch-netex;
+        npm run fetch-de-netex;
         currentobj=$(aws s3api head-object --bucket $DO_SPACES_BUCKET_NAME --key netex-germany.zip);
-        newhash=$(cat netex.zip | md5sum);
+        newhash=$(cat de-netex.zip | md5sum);
         if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
         then
-          aws s3 cp --acl public-read netex.zip s3://"$DO_SPACES_BUCKET_NAME"/netex-germany.zip
+          aws s3 cp --acl public-read de-netex.zip s3://"$DO_SPACES_BUCKET_NAME"/netex-germany.zip
         else
           echo 'file unchanged, skipping.'
         fi;
@@ -121,12 +121,30 @@ jobs:
         DO_SPACES_BUCKET_NAME: ${{ secrets.DO_SPACES_BUCKET_NAME }}
       run: |
         set -e;
-        npm run fetch-zhv;
+        npm run fetch-de-zhv;
         currentobj=$(aws s3api head-object --bucket $DO_SPACES_BUCKET_NAME --key zhv.zip);
-        newhash=$(cat zhv.zip | md5sum);
+        newhash=$(cat de-zhv.zip | md5sum);
         if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
         then
-          aws s3 cp --acl public-read zhv.zip s3://"$DO_SPACES_BUCKET_NAME"/zhv.zip
+          aws s3 cp --acl public-read de-zhv.zip s3://"$DO_SPACES_BUCKET_NAME"/zhv.zip
+        else
+          echo 'file unchanged, skipping.'
+        fi;
+
+    - name: "Fetch and upload feed: DE_NRW_GTFS"
+      if: ${{ success() || failure() }} # this should allow the other steps to run, but should still mark the workflow as failing
+      env:
+        OPENDATA_OEPNV_EMAIL: ${{ secrets.OPENDATA_OEPNV_EMAIL }}
+        OPENDATA_OEPNV_PASSWORD: ${{ secrets.OPENDATA_OEPNV_PASSWORD }}
+        DO_SPACES_BUCKET_NAME: ${{ secrets.DO_SPACES_BUCKET_NAME }}
+      run: |
+        set -e;
+        npm run fetch-de-nrw-gtfs;
+        currentobj=$(aws s3api head-object --bucket $DO_SPACES_BUCKET_NAME --key de/nrw-gtfs.zip);
+        newhash=$(cat de-nrw-gtfs.zip | md5sum);
+        if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
+        then
+          aws s3 cp --acl public-read de-nrw-gtfs.zip s3://"$DO_SPACES_BUCKET_NAME"/de/nrw-gtfs.zip
         else
           echo 'file unchanged, skipping.'
         fi;
