switch job order

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -92,24 +92,6 @@ jobs:
           echo 'file unchanged, skipping.'
         fi;
 
-    - name: "Fetch and upload feed: DE_NETEX"
-      if: ${{ success() || failure() }} # this should allow the other steps to run, but should still mark the workflow as failing
-      env:
-        OPENDATA_OEPNV_EMAIL: ${{ secrets.OPENDATA_OEPNV_EMAIL }}
-        OPENDATA_OEPNV_PASSWORD: ${{ secrets.OPENDATA_OEPNV_PASSWORD }}
-        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
-      run: |
-        set -e;
-        npm run fetch-de-netex;
-        currentobj=$(aws s3api head-object --bucket $S3_BUCKET_NAME --key de/netex.zip || echo 'not-yet-existing');
-        newhash=$(cat de-netex.zip | md5sum);
-        if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
-        then
-          aws s3 cp --checksum-algorithm=CRC32 --acl public-read de-netex.zip s3://"$S3_BUCKET_NAME"/de/netex.zip
-        else
-          echo 'file unchanged, skipping.'
-        fi;
-
     - name: "Fetch and upload feed: DE_ZHV"
       if: ${{ success() || failure() }} # this should allow the other steps to run, but should still mark the workflow as failing
       env:
@@ -141,6 +123,24 @@ jobs:
         if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
         then
           aws s3 cp --checksum-algorithm=CRC32 --acl public-read ./src/linked-data/zhv-de/data/output.ttl.gz s3://"$S3_BUCKET_NAME"/de/zhv.ttl.gz
+        else
+          echo 'file unchanged, skipping.'
+        fi;
+
+    - name: "Fetch and upload feed: DE_NETEX"
+      if: ${{ success() || failure() }} # this should allow the other steps to run, but should still mark the workflow as failing
+      env:
+        OPENDATA_OEPNV_EMAIL: ${{ secrets.OPENDATA_OEPNV_EMAIL }}
+        OPENDATA_OEPNV_PASSWORD: ${{ secrets.OPENDATA_OEPNV_PASSWORD }}
+        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
+      run: |
+        set -e;
+        npm run fetch-de-netex;
+        currentobj=$(aws s3api head-object --bucket $S3_BUCKET_NAME --key de/netex.zip || echo 'not-yet-existing');
+        newhash=$(cat de-netex.zip | md5sum);
+        if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
+        then
+          aws s3 cp --checksum-algorithm=CRC32 --acl public-read de-netex.zip s3://"$S3_BUCKET_NAME"/de/netex.zip
         else
           echo 'file unchanged, skipping.'
         fi;
