add scraper for swedish gtfs feed (:sweden:)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -197,3 +197,20 @@ jobs:
         else
           echo 'file unchanged, skipping.'
         fi;
+
+    - name: "Fetch and upload feed: SE_GTFS"
+      if: ${{ success() || failure() }} # this should allow the other steps to run, but should still mark the workflow as failing
+      env:
+        TRAFIKLAB_API_KEY: ${{ secrets.TRAFIKLAB_API_KEY }}
+        DO_SPACES_BUCKET_NAME: ${{ secrets.DO_SPACES_BUCKET_NAME }}
+      run: |
+        set -e;
+        npm run fetch-se-gtfs;
+        currentobj=$(aws s3api head-object --bucket $DO_SPACES_BUCKET_NAME --key se/gtfs.zip || echo 'not-yet-existing');
+        newhash=$(cat se-gtfs.zip | md5sum);
+        if [ $(echo $currentobj | grep $newhash | wc -l) -ne 1 ]
+        then
+          aws s3 cp --acl public-read se-gtfs.zip s3://"$DO_SPACES_BUCKET_NAME"/se/gtfs.zip
+        else
+          echo 'file unchanged, skipping.'
+        fi;
